apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  selector:
    app: messaging-blue  # Change to messaging-green to switch traffic
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP